(require 'cl)

(defvar *my-quotes*
  '("Give someone Fortran, he has Fortran. Give someone Lisp, he has any language he pleases. -- Guy Steele"
    "Premature optimisation is the root of all evil in programming. -- C. A. R. Hoare"
    "The best way to predict the future is to implement it. -- David Heinemeier Hansson"
    "PHP: Training wheels without the bike. -- TNX"
    "God is Real, unless declared Integer. -- J.Allan Toogood, FORTRAN programmer"
    "C is quirky, flawed, and an enormous success. -- Dennis M. Ritchie"
    "C++: an octopus made by nailing extra legs onto a dog. -- Steve Taylor"
    "Fifty years of programming language research, and we end up with C++? -- Richard A. O'Keefe"
    "In C++ it's harder to shoot yourself in the foot, but when you do, you blow off your whole leg. -- Bjarne Stroustrup"
    "The use of COBOL cripples the mind ; its teaching should therefore be regarded as a criminal offense. -- Edsger Dijkstra"
    "There's no obfuscated Perl contest because it's pointless. -- Jeff Polk (Source). Note that there was in fact an Obfuscated Perl contest. "
    "(What the world needs (I think) is not (a Lisp (with fewer parentheses)) but (an English (with more.))) -- Brian Hayes, 'The Semicolon Wars', American Scientist"
    "Programs must be written for people to read, and only incidentally for machines to execute. -- Abelson & Sussman, SICP, preface to the first edition "
    "That language is an instrument of human reason, and not merely a medium for the expression of thought, is a truth generally admitted. -- George Boole, quoted in Iverson's Turing Award Lecture "
    "Lisp is the greatest single programming language ever designed -- Alan Kay, on Lisp"
    "Greenspun's Tenth Rule of Programming: any sufficiently complicated C or Fortran program contains an ad hoc informally-specified bug-ridden slow implementation of half of Common Lisp. -- Philip Greenspun (\"Including Common Lisp\" -- as added by Robert Morris)"
    "Lisp has jokingly been called 'the most intelligent way to misuse a computer'. I think that description is a great compliment because it transmits the full flavor of liberation: it has assisted a number of our most gifted fellow humans in thinking previously impossible thoughts. -- Edsger Dijkstra, CACM, 15:10 "
    "Lisp ... made me aware that software could be close to executable mathematics. -- L. Peter Deutsch"
    "SQL, Lisp, and Haskell are the only programming languages that I've seen where one spends more time thinking than typing. -- Philip Greenspun (\"And Prolog\" -- by Jianshi Huang)"
    "The key to performance is elegance, not battalions of special cases. -- Jon Bentley and Doug McIlroy"
    "Haskell is faster than C++, more concise than Perl, more regular than Python, more flexible than Ruby, more typeful than C#, more robust than Java, and has absolutely nothing in common with PHP. -- Autrijus Tang"
    "Given enough eyeballs, all bugs are shallow. -- Eric S. Raymond (Linus' Law)"
    "If debugging is the process of removing bugs, then programming must be the process of putting them in. -- Edsger W. Dijkstra"
    "Testing can only prove the presence of bugs, not their absence. -- Edsger W. Dijkstra "
    "The paradox of software testing: In theory, testing software for correctness is impossible. In practice, it is given to freshmen because it's the least demanding task available."
    "A documented bug is not a bug      ; it is a feature. -- James P. MacLennan"
    "Real Programmers always confuse Christmas and Halloween because Oct31 == Dec25. -- Andrew Rutherford "
    "Real Programmers aren't afraid to use GOTOs."
    "Real Programmers don't need comments -- the code is obvious. "
    "Real Programmers remember phone numbers in binary."
    "Should array indices start at 0 or 1? My compromise of 0.5 was rejected without, I thought, proper consideration. -- (Stan Kelly-Bootle)"
    "Software is like sex: It's better when it's free. -- (Linus Torvalds)"
    "If you don't think carefully, you might think that programming is just typing statements in a programming language. -- (Ward Cunningham)"
    "A language that doesn't have everything is actually easier to program in than some that do. -- (Dennis M Ritchie)"
    "Projects promoting programming in natural language are intrinsically doomed to fail. -- (Edsger Dijkstra)"
    "First learn computer science and all the theory. Next develop a programming style. Then forget all that and just hack. -- (George Carrette)"
    "I fear the the new object-oriented systems may suffer the fate of LISP, in that they can do many things, but the complexity of the class hierarchies may cause them to collapse under their own weight. -- (Bill Joy)"
    "You can either have software quality or you can have pointer arithmetic, but you cannot have both at the same time. -- (Bertrand Meyer)"
    "Syntax, my lad. It has been restored to the highest place in the republic. -- (John Steinbeck)"
    "If the programmer can simulate a construct faster than a compiler can implement the construct itself, then the compiler writer has blown it badly. -- (Guy Steele)"
    "If buffer overflows are ever controlled, it won't be due to mere crashes, but due to their making systems vulnerable to hackers. Software crashes due to mere incompetence apparently don't raise any eyebrows, because no one wants to fault the incompetent programmer and his incompetent boss. -- (Henry Baker)"
    "Memory is like an orgasm. It's a lot better if you don't have to fake it. -- (Seymour Cray)"
    "APL is a write-only language. I can write programs in APL, but I can't read any of them. -- (Roy Keir)"
    "Historically, languages designed for other people to use have been bad: Cobol, PL/I, Pascal, Ada, C++. The good languages have been those that were designed for their own creators: C, Perl, Smalltalk, Lisp. -- (Paul Graham)"
    "PL/I and Ada started out with all the bloat, were very daunting languages, and got bad reputations (deservedly). C++ has shown that if you slowly bloat up a language over a period of years, people don't seem to mind as much. -- (James Hague)"
    "Other advanced languages, such as assembler and C, were not terribly complex in themselves, but the environments in which applications were developed were downright weird, with mines scattered about everywhere, ready to blow the inattentive programmer out of the water. -- (Bruce Tognazzini)"
    "APL is like a diamond. It has a beautiful crystal structure; all of its parts are related in a uniform and elegant way. But if you try to extend this structure in any way - even by adding another diamond - you get an ugly kludge. LISP, on the other hand, is like a ball of mud. You can add any amount of mud to it and it still looks like a ball of mud. -- (Joel Moses)"
    "If you're masochistic enough to program in ADA, we're not going to stop you. -- (Matt Welsh)"
    "One of the main causes of the fall of the Roman Empire was that, lacking zero, they had no way to indicate successful termination of their C programs. -- (Robert Firth)"
    "Being really good at C++ is like being really good at using rocks to sharpen sticks. -- (Thant Tessman)"
    "I invented the term Object-Oriented, and I can tell you I did not have C++ in mind. -- (Alan Kay)"
    "Eiffel borrows quite heavily from some earlier programming languages and I am sure that if we had found a good programming construct in C we would have used it as well. -- (Bertrand Meyer)"
    "Whenever the C++ language designers had two competing ideas as to how they should solve some problem, they said, OK, we'll do them both. So the language is too baroque for my taste. -- (Donald E Knuth)"
    "Unix and C are the ultimate computer viruses. -- (Richard P Gabriel)"
    "It has been discovered that C++ provides a remarkable facility for concealing the trival details of a program -- such as where its bugs are. -- (David Keppel)"
    "Cobol has almost no fervent enthusiasts. As a programming tool, it has roughly the sex appeal of a wrench. -- (Charles Petzold)"
    "A computer without COBOL and FORTRAN is like a piece of chocolate cake without ketchup or mustard. -- (John Krueger)"
    "You can tell how far we have to go, when FORTRAN is the language of supercomputers. -- (Steven Feiner)"
    "Eiffel has perhaps the image of a cruel professor giving students tough assignments and not accepting excuses. C/C++, on the other hand, has an almost sports-car image. -- (John Nagle)"
    "C++ is the only current language making COBOL look good. -- (Bertrand Meyer)"
    "The very architecture of almost every computer today is designed to optimize the performance of Fortran programs and its operating-system-level sister, C. -- (Peter Gabriel)"
    "Anyone could learn Lisp in one day, except that if they already knew Fortran, it would take three days. -- (Marvin Minsky)"
    "Please don't fall into the trap of believing that I am terribly dogmatical about [the goto statement]. I have the uncomfortable feeling that others are making a religion out of it, as if the conceptual problems of programming could be solved by a single trick, by a simple form of coding discipline! -- (Edsger Dijkstra)"
    "Java is the most distressing thing to happen to computing since MS-DOS. -- (Alan Kay)"
    "Your development cycle is much faster because Java is interpreted. The compile-link-load-test-crash-debug cycle is obsolete. -- -- (James Gosling)"
    "Actually, I'm trying to make Ruby natural, not simple. -- (Yukihiro Matz Matsumoto)"
    "Perl: The only language that looks the same before and after RSA encryption. -- (Keith Bostic) (\"And J!\" -- Jianshi Huang)"
    "A Lisp programmer knows the value of everything, but the cost of nothing. -- (Alan Perlis)"
    "Java: the elegant simplicity of C++ and the blazing speed of Smalltalk. -- (Jan Steinman)"
    "Like the creators of sitcoms or junk food or package tours, Java's designers were consciously designing a product for people not as smart as them. -- (Paul Graham)"
    "High thoughts must have a high language. -- (Aristophanes)"
    "The more of an IT flavor the job descriptions had, the less dangerous was the company. The safest kind were the ones that wanted Oracle experience. You never had to worry about those. You were also safe if they said they wanted C++ or Java developers. If they wanted Perl or Python programmers, that would be a bit frightening. If I had ever seen a job posting looking for Lisp hackers, I would have been really worried. -- (Paul Graham)"
    "I suppose I should learn Lisp, but it seems so foreign. - Paul Graham, Nov 1983"
    "Documentation is like sex: when it is good, it is very, very good; and when it is bad, it is better than nothing. -- (Dick Brandon)"
    "Any sufficiently advanced bug is indistinguishable from a feature. -- (Rich Kulawiec)"
    "COBOL programs are an exercise in Artificial Inelegance. -- Anonymous"
    "There are 10 types of people: those who understand binary, and those who do not understand it. -- Anonymous"
    "The tools we use have a profound (and devious!) influence on our thinking habits, and, therefore, on our thinking abilities. -- Edsger Dijkstra"
    "About the use of language: it is impossible to sharpen a pencil with a blunt axe. It is equally vain to try to do it with ten blunt axes instead. -- Edsger Dijkstra (\"And it is equally unwise to try to do it with a sharp axe!\" -- Jianshi Huang)"
    "If people do not believe that mathematics is simple, it is only because they do not realize how complicated life is.  ~John Louis von Neumann "
    "Black holes result from God dividing the universe by zero.  ~Author Unknown"
    "The essence of mathematics is not to make simple things complicated, but to make complicated things simple.  ~S. Gudder"
    "Go down deep enough into anything and you will find mathematics.  ~Dean Schlicter"
    "It is not the job of mathematicians... to do correct arithmetical operations.  It is the job of bank accountants.  ~Samuil Shchatunovski"
    "A mathematician is a device for turning coffee into theorems. ~Paul Erdos"
    "I'm a bit like an operating system really... 'multitasking' between these two OHPs, 'interrupting' you, ... 'sending you to sleep'...  -- From a lecturer"
    "Mathematics is an independent world created out of pure intelligence."
    "We've all heard that a million monkeys banging on a million typewriters will eventually reproduce the entire works of Shakespeare.  Now, thanks to the internet, we know this is not true. -- Professor Robert Silensky"
    "Mathematics is like love; a simple idea, but it can get complicated. -- Anonymous"
    "Lisp is the red pill. -- John Fraser, comp.lang.lisp"
    "In Lisp, if you want to do aspect-oriented programming, you just do a bunch of macros and you're there. In Java, you have to get Gregor Kiczales to go out and start a new company, taking months and years and try to get that to work. Lisp still has the advantage there, it's just a question of people wanting that.  -- Peter Norvig"
    "LISP has survived for 21 years because it is an approximate local optimum in the space of programming languages. -- John McCarthy (1980)"
    "LISP stands for: Lots of Insane Stupid Parentheses. -- Anonymous"
    "Programming is fun again. -- Jianshi Huang, On his first encounter with Lisp"
    "Some languages are designed for writing algorithms, some languages are designed for designing languages. -- Jianshi Huang"
    "Some languages are invented to solve new problems, some problems are solved to invent new languages. -- Jianshi Huang"
    "Fools ignore complexity ; pragmatists suffer it; experts avoid it; geniuses remove it. -- Alan Perlis"
    "Let us change our traditional attitude to the construction of programs. Instead of imagining that our main task is to instruct a computer what to do, let us concentrate rather on explaining to human beings what we want a computer to do. -- Donald Knuth"
    "You're bound to be unhappy if you optimize everything. -- Donald Knuth"
    "c++ ; /* this makes c bigger but returns the old value */ -- Unknown"
    "Computer Science is no more about computers than astronomy is about telescopes. -- Edsger Dijkstra"
    "Everyone needs computer programming. It will be the way we speak to the servants. -- John McCarthy"
    "If a train station is a place where a train stops, what's a workstation?  -- unknown (to me, at least)"
    "Remember - if all you have is an axe, every problem looks like hours of fun.  -- Frossie"
    "Just getting something to work usually means writing reams of code fast, like a Stephen King novel, but making it maintainable and high-quality code that really expresses the ideas well, is like writing poetry.  Art is taking away.  -- Erik Naggum, comp.lang.lisp "
    "Finding a needle in a haystack is a lot easier if you burn down the haystack and scan the ashes with a metal detector. -- the Silicon Valley Tarot (another one nicked from David Rush) "
    "Structure is _nothing_ if it is all you got.  Skeletons _spook_ people if they try to walk around on their own.  I really wonder why XML does not.  -- Erik Naggum, comp.lang.lisp "
    "Enlightenment is probably antithetical to impatience. -- Erik Naggum, comp.lang.lisp "
    " Research results from the psychology of programming [Petre89] indicate that expertise in programming is far more strongly related to the number of dif- ferent programming styles understood by an individual that it is to the number of years experience in programming [Budd95].  -- Timothy Budd"
    " It is my aim to first enumerate experience and then to proof with reason why it must act in this way. -- Leonardo da Vinci"
    ))

(defvar *my-quote-length* (length *my-quotes*))

(defun random-quote ()
  (nth (random *my-quote-length*) *my-quotes*))

