(require 'cl-lookup)
(defvar cl-lookup-cl-who-root "http://weitz.de/cl-who/")

(mapc #'(lambda (entry)
	  (destructuring-bind (name path) entry
	    (let ((symbol (intern (downcase name) cl-lookup-obarray)))
	      (if (boundp symbol)
		  (pushnew path (symbol-value symbol) :test #'equal)
		  (set symbol `(,path))))))
      '(("cl-who" (cl-lookup-cl-who-root ""))
        ("cl-who:*attribute-quote-char*" (cl-lookup-cl-who-root "#*attribute-quote-char*"))
        ("cl-who:*downcase-tokens-p*" (cl-lookup-cl-who-root "#*downcase-tokens-p*"))
        ("cl-who:*escape-char-p*" (cl-lookup-cl-who-root "#*escape-char-p*"))
        ("cl-who:*html-empty-tag-aware-p*" (cl-lookup-cl-who-root "#*html-empty-tag-aware-p*"))
        ("cl-who:*html-empty-tags*" (cl-lookup-cl-who-root "#*html-empty-tags*"))
        ("cl-who:*prologue*" (cl-lookup-cl-who-root "#*prologue*"))
        ("cl-who:conc" (cl-lookup-cl-who-root "#conc"))
        ("cl-who:convert-attributes" (cl-lookup-cl-who-root "#convert-attributes"))
        ("cl-who:convert-tag-to-string-list" (cl-lookup-cl-who-root "#convert-tag-to-string-list"))
        ("cl-who:esc" (cl-lookup-cl-who-root "#esc"))
        ("cl-who:escape-char" (cl-lookup-cl-who-root "#escape-char"))
        ("cl-who:escape-char-all" (cl-lookup-cl-who-root "#escape-char-all"))
        ("cl-who:escape-char-iso-8859-1" (cl-lookup-cl-who-root "#escape-char-iso-8859-1"))
        ("cl-who:escape-char-minimal" (cl-lookup-cl-who-root "#escape-char-minimal"))
        ("cl-who:escape-char-minimal-plus-quotes" (cl-lookup-cl-who-root "#escape-char-minimal-plus-quotes"))
        ("cl-who:escape-string" (cl-lookup-cl-who-root "#escape-string"))
        ("cl-who:escape-string-all" (cl-lookup-cl-who-root "#escape-string-all"))
        ("cl-who:escape-string-iso-8859" (cl-lookup-cl-who-root "#escape-string-iso-8859"))
        ("cl-who:escape-string-iso-8859-1" (cl-lookup-cl-who-root "#escape-string-iso-8859-1"))
        ("cl-who:escape-string-minimal" (cl-lookup-cl-who-root "#escape-string-minimal"))
        ("cl-who:escape-string-minimal-plus-quotes" (cl-lookup-cl-who-root "#escape-string-minimal-plus-quotes"))
        ("cl-who:fmt" (cl-lookup-cl-who-root "#fmt"))
        ("cl-who:htm" (cl-lookup-cl-who-root "#htm"))
        ("cl-who:html-mode" (cl-lookup-cl-who-root "#html-mode"))
        ("cl-who:show-html-expansion" (cl-lookup-cl-who-root "#show-html-expansion"))
        ("cl-who:str" (cl-lookup-cl-who-root "#str"))
        ("cl-who:with-html-output" (cl-lookup-cl-who-root "#with-html-output"))
        ("cl-who:with-html-output-to-string" (cl-lookup-cl-who-root "#with-html-output-to-string"))
        ))

(provide 'cl-lookup-cl-who)