(require 'cl-lookup)
(defvar cl-lookup-acl-operators-system-root "http://www.franz.com/support/documentation/8.2/doc/operators/system/")
(defvar cl-lookup-acl-variables-system-root "http://www.franz.com/support/documentation/8.2/doc/variables/system/")
(defvar cl-lookup-acl-classes-system-root "http://www.franz.com/support/documentation/8.2/doc/classes/system/")

(mapc #'(lambda (entry)
	  (destructuring-bind (name path) entry
	    (let ((symbol (intern (downcase name) cl-lookup-obarray)))
	      (if (boundp symbol)
		  (pushnew path (symbol-value symbol) :test #'equal)
		  (set symbol `(,path))))))
      '(
        ("system:*all-processes*" (cl-lookup-acl-variables-system-root "s_all-processes_s.htm"))
        ("system:*autoload-search-list*" (cl-lookup-acl-variables-system-root "s_autoload-search-list_s.htm"))
        ("system:*compilation-unit-environment*" (cl-lookup-acl-variables-system-root "s_compilation-unit-environment_s.htm"))
        ("system:*compile-file-environment*" (cl-lookup-acl-variables-system-root "s_compile-file-environment_s.htm"))
        ("system:*current-process*" (cl-lookup-acl-variables-system-root "s_current-process_s.htm"))
        ("system:*current-thread*" (cl-lookup-acl-variables-system-root "s_current-thread_s.htm"))
        ("system:*disallow-scheduling*" (cl-lookup-acl-variables-system-root "s_disallow-scheduling_s.htm"))
        ("system:*e*" (cl-lookup-acl-variables-system-root "s_e_s.htm"))
        ("system:*evaluation-environment*" (cl-lookup-acl-variables-system-root "s_evaluation-environment_s.htm"))
        ("system:*exit-cleanup-forms*" (cl-lookup-acl-variables-system-root "s_exit-cleanup-forms_s.htm"))
        ("system:*impossible-load-address*" (cl-lookup-acl-variables-system-root "s_impossible-load-address_s.htm"))
        ("system:*interpreter-environment*" (cl-lookup-acl-variables-system-root "s_interpreter-environment_s.htm"))
        ("system:*language-prefixes*" (cl-lookup-acl-variables-system-root "s_language-prefixes_s.htm"))
        ("system:*language-suffixes*" (cl-lookup-acl-variables-system-root "s_language-suffixes_s.htm"))
        ("system:*load-search-list*" (cl-lookup-acl-variables-system-root "s_load-search-list_s.htm"))
        ("system:*patches*" (cl-lookup-acl-variables-system-root "s_patches_s.htm"))
        ("system:*require-search-list*" (cl-lookup-acl-variables-system-root "s_require-search-list_s.htm"))
        ("system:*source-file-frobbers*" (cl-lookup-acl-variables-system-root "s_source-file-frobbers_s.htm"))
        ("system:*source-file-types*" (cl-lookup-acl-variables-system-root "s_source-file-types_s.htm"))
        ("system:*temporary-directory*" (cl-lookup-acl-variables-system-root "s_temporary-directory_s.htm"))
        ("system:*tilde-expand-namestrings*" (cl-lookup-acl-variables-system-root "s_tilde-expand-namestrings_s.htm"))
        ("system:abort-patch-compiling" (cl-lookup-acl-variables-system-root "abort-patch-compiling.htm"))
        ("system:abort-patch-loading" (cl-lookup-acl-variables-system-root "abort-patch-loading.htm"))
        ("system:augment-environment" (cl-lookup-acl-operators-system-root "augment-environment.htm"))
        ("system:block-information" (cl-lookup-acl-operators-system-root "block-information.htm"))
        ("system:ce-get" (cl-lookup-acl-operators-system-root "ce-get.htm"))
        ("system:ce-putprop" (cl-lookup-acl-operators-system-root "ce-putprop.htm"))
        ("system:command-line-argument" (cl-lookup-acl-operators-system-root "command-line-argument.htm"))
        ("system:command-line-argument-count" (cl-lookup-acl-operators-system-root "command-line-argument-count.htm"))
        ("system:command-line-arguments" (cl-lookup-acl-operators-system-root "command-line-arguments.htm"))
        ("system:constant-value" (cl-lookup-acl-operators-system-root "constant-value.htm"))
        ("system:copy-file" (cl-lookup-acl-operators-system-root "copy-file.htm"))
        ("system:declaration-information" (cl-lookup-acl-operators-system-root "declaration-information.htm"))
        ("system:define-declaration" (cl-lookup-acl-operators-system-root "define-declaration.htm"))
        ("system:defpatch" (cl-lookup-acl-operators-system-root "defpatch.htm"))
        ("system:ensure-current-process" (cl-lookup-acl-operators-system-root "ensure-current-process.htm"))
        ("system:ensure-portable-walking-environment" (cl-lookup-acl-operators-system-root "ensure-portable-walking-environment.htm"))
        ("system:flush-codevectors" (cl-lookup-acl-operators-system-root "flush-codevectors.htm"))
        ("system:funcall-after-idle-timeout" (cl-lookup-acl-operators-system-root "funcall-after-idle-timeout.htm"))
        ("system:function-information" (cl-lookup-acl-operators-system-root "function-information.htm"))
        ("system:getenv" (cl-lookup-acl-operators-system-root "getenv.htm"))
        ("system:global-symbol-value" (cl-lookup-acl-operators-system-root "global-symbol-value.htm"))
        ("system:gsgc-parameter" (cl-lookup-acl-operators-system-root "gsgc-parameter.htm"))
        ("system:gsgc-parameters" (cl-lookup-acl-operators-system-root "gsgc-parameters.htm"))
        ("system:gsgc-step-generation" (cl-lookup-acl-operators-system-root "gsgc-step-generation.htm"))
        ("system:gsgc-switch" (cl-lookup-acl-operators-system-root "gsgc-switch.htm"))
        ("system:initialize-sigio-handling" (cl-lookup-acl-operators-system-root "initialize-sigio-handling.htm"))
        ("system:lispval-storage-type" (cl-lookup-acl-operators-system-root "lispval-storage-type.htm"))
        ("system:load-patches" (cl-lookup-acl-operators-system-root "load-patches.htm"))
        ("system:make-compilation-unit-environment" (cl-lookup-acl-operators-system-root "make-compilation-unit-environment.htm"))
        ("system:make-compile-file-environment" (cl-lookup-acl-operators-system-root "make-compile-file-environment.htm"))
        ("system:make-temp-file-name" (cl-lookup-acl-operators-system-root "make-temp-file-name.htm"))
        ("system:memref" (cl-lookup-acl-operators-system-root "memref.htm"))
        ("system:memref-int" (cl-lookup-acl-operators-system-root "memref-int.htm"))
        ("system:os-wait" (cl-lookup-acl-operators-system-root "os-wait.htm"))
        ("system:pointer-storage-type" (cl-lookup-acl-operators-system-root "pointer-storage-type.htm"))
        ("system:presto-build-lib" (cl-lookup-acl-operators-system-root "presto-build-lib.htm"))
        ("system:presto-fasl-set" (cl-lookup-acl-operators-system-root "presto-fasl-set.htm"))
        ("system:prestop" (cl-lookup-acl-operators-system-root "prestop.htm"))
        ("system:processor-affinity-mask" (cl-lookup-acl-variables-system-root "processor-affinity-mask.htm"))
        ("system:reap-os-subprocess" (cl-lookup-acl-operators-system-root "reap-os-subprocess.htm"))
        ("system:record-code-vectors" (cl-lookup-acl-operators-system-root "record-code-vectors.htm"))
        ("system:record-strings" (cl-lookup-acl-operators-system-root "record-strings.htm"))
        ("system:remove-sigio-handler" (cl-lookup-acl-operators-system-root "remove-sigio-handler.htm"))
        ("system:resize-areas" (cl-lookup-acl-operators-system-root "resize-areas.htm"))
        ("system:scheduler-in-control-p" (cl-lookup-acl-operators-system-root "scheduler-in-control-p.htm"))
        ("system:scheduler-running-p" (cl-lookup-acl-operators-system-root "scheduler-running-p.htm"))
        ("system:set-sigio-handler" (cl-lookup-acl-operators-system-root "set-sigio-handler.htm"))
        ("system:set-splash-bitmap" (cl-lookup-acl-variables-system-root "set-splash-bitmap.htm"))
        ("system:set-stack-cushion" (cl-lookup-acl-operators-system-root "set-stack-cushion.htm"))
        ("system:sigio-supported-p" (cl-lookup-acl-operators-system-root "sigio-supported-p.htm"))
        ("system:stack-cushion" (cl-lookup-acl-operators-system-root "stack-cushion.htm"))
        ("system:tag-information" (cl-lookup-acl-operators-system-root "tag-information.htm"))
        ("system:temporary-directory" (cl-lookup-acl-operators-system-root "temporary-directory.htm"))
        ("system:tmp-mnt-frobber" (cl-lookup-acl-operators-system-root "tmp-mnt-frobber.htm"))
        ("system:update-allegro" (cl-lookup-acl-operators-system-root "update-allegro.htm"))
        ("system:user-name" (cl-lookup-acl-operators-system-root "user-name.htm"))
        ("system:variable-information" (cl-lookup-acl-operators-system-root "variable-information.htm"))
        ("system:with-command-line-arguments" (cl-lookup-acl-operators-system-root "with-command-line-arguments.htm"))
        ("system:with-timeout" (cl-lookup-acl-operators-system-root "with-timeout.htm"))
        ("system:without-scheduling" (cl-lookup-acl-operators-system-root "without-scheduling.htm"))
        ("system:write-codevectors" (cl-lookup-acl-operators-system-root "write-codevectors.htm"))
        ))

(provide 'cl-lookup-acl-system)