(require 'cl-lookup)
(defvar cl-lookup-acl-operators-net.aserve.client-root "http://www.franz.com/support/documentation/8.2/doc/aserve/aserve.html")
(defvar cl-lookup-acl-variables-net.aserve.client-root "http://www.franz.com/support/documentation/8.2/doc/aserve/aserve.html")

(mapc #'(lambda (entry)
	  (destructuring-bind (name path) entry
	    (let ((symbol (intern (downcase name) cl-lookup-obarray)))
	      (if (boundp symbol)
		  (pushnew path (symbol-value symbol) :test #'equal)
		  (set symbol `(,path))))))
      '(
        ("net.aserve.client:client-request" (cl-lookup-acl-variables-net.aserve.client-root "#v-client-request"))
        ("net.aserve.client:client-request-close" (cl-lookup-acl-operators-net.aserve.client-root "#f-client-request-close"))
        ("net.aserve.client:client-request-cookies" (cl-lookup-acl-operators-net.aserve.client-root "#f-client-request-cookies"))
        ("net.aserve.client:client-request-headers" (cl-lookup-acl-operators-net.aserve.client-root "#f-client-request-headers"))
        ("net.aserve.client:client-request-protocol" (cl-lookup-acl-operators-net.aserve.client-root "#f-client-request-protocol"))
        ("net.aserve.client:client-request-read-sequence" (cl-lookup-acl-operators-net.aserve.client-root "#f-client-request-read-sequence"))
        ("net.aserve.client:client-request-response-code" (cl-lookup-acl-operators-net.aserve.client-root "#f-client-request-response-code"))
        ("net.aserve.client:client-request-response-comment" (cl-lookup-acl-operators-net.aserve.client-root "#f-client-request-response-comment"))
        ("net.aserve.client:client-request-socket" (cl-lookup-acl-operators-net.aserve.client-root "#f-client-request-socket"))
        ("net.aserve.client:client-request-uri" (cl-lookup-acl-operators-net.aserve.client-root "#f-client-request-uri"))
        ("net.aserve.client:client-response-header-value" (cl-lookup-acl-operators-net.aserve.client-root "#f-client-response-header-value"))
        ("net.aserve.client:compute-digest-authorization" (cl-lookup-acl-operators-net.aserve.client-root "#f-compute-digest-authorization"))
        ("net.aserve.client:cookie-item" (cl-lookup-acl-variables-net.aserve.client-root "#v-cookie-item"))
        ("net.aserve.client:cookie-item-expires" (cl-lookup-acl-operators-net.aserve.client-root "#f-cookie-item-expires"))
        ("net.aserve.client:cookie-item-name" (cl-lookup-acl-operators-net.aserve.client-root "#f-cookie-item-name"))
        ("net.aserve.client:cookie-item-path" (cl-lookup-acl-operators-net.aserve.client-root "#f-cookie-item-path"))
        ("net.aserve.client:cookie-item-secure" (cl-lookup-acl-operators-net.aserve.client-root "#f-cookie-item-secure"))
        ("net.aserve.client:cookie-item-value" (cl-lookup-acl-operators-net.aserve.client-root "#f-cookie-item-value"))
        ("net.aserve.client:cookie-jar" (cl-lookup-acl-variables-net.aserve.client-root "#v-cookie-jar"))
        ("net.aserve.client:digest-authorization" (cl-lookup-acl-variables-net.aserve.client-root "#v-digest-authorization"))
        ("net.aserve.client:digest-password" (cl-lookup-acl-operators-net.aserve.client-root "#f-digest-password"))
        ("net.aserve.client:digest-realm" (cl-lookup-acl-operators-net.aserve.client-root "#f-digest-realm"))
        ("net.aserve.client:digest-username" (cl-lookup-acl-operators-net.aserve.client-root "#f-digest-username"))
        ("net.aserve.client:do-http-request" (cl-lookup-acl-operators-net.aserve.client-root "#f-do-http-request"))
        ("net.aserve.client:http-copy-file" (cl-lookup-acl-operators-net.aserve.client-root "#f-http-copy-file"))
        ("net.aserve.client:make-http-client-request" (cl-lookup-acl-operators-net.aserve.client-root "#f-make-http-client-request"))
        ("net.aserve.client:read-client-response-headers" (cl-lookup-acl-operators-net.aserve.client-root "#f-read-client-response-headers"))
        ("net.aserve.client:read-response-body" (cl-lookup-acl-operators-net.aserve.client-root "#f-read-response-body"))
        ))

(provide 'cl-lookup-acl-net.aserve.client)