(require 'cl-lookup)
(defvar cl-lookup-acl-operators-dbi-root "http://www.franz.com/support/documentation/8.2/doc/operators/dbi/")
(defvar cl-lookup-acl-variables-dbi-root "http://www.franz.com/support/documentation/8.2/doc/variables/dbi/")
(defvar cl-lookup-acl-classes-dbi-root "http://www.franz.com/support/documentation/8.2/doc/classes/dbi/")

(mapc #'(lambda (entry)
	  (destructuring-bind (name path) entry
	    (let ((symbol (intern (downcase name) cl-lookup-obarray)))
	      (if (boundp symbol)
		  (pushnew path (symbol-value symbol) :test #'equal)
		  (set symbol `(,path))))))
      '(
        ("dbi:*auto-trim-strings*" (cl-lookup-acl-variables-dbi-root "s_auto-trim-strings_s.htm"))
        ("dbi:*default-database*" (cl-lookup-acl-variables-dbi-root "s_default-database_s.htm"))
        ("dbi:*default-odbc-external-format*" (cl-lookup-acl-variables-dbi-root "s_default-odbc-external-format_s.htm"))
        ("dbi:*null-value*" (cl-lookup-acl-variables-dbi-root "s_null-value_s.htm"))
        ("dbi:*use-simple-fetch-loop-for-column-data*" (cl-lookup-acl-variables-dbi-root "s_use-simple-fetch-loop-for-column-data_s.htm"))
        ("dbi:bind-parameter" (cl-lookup-acl-operators-dbi-root "bind-parameter.htm"))
        ("dbi:close-query" (cl-lookup-acl-operators-dbi-root "close-query.htm"))
        ("dbi:column-count" (cl-lookup-acl-variables-dbi-root "column-count.htm"))
        ("dbi:column-value" (cl-lookup-acl-variables-dbi-root "column-value.htm"))
        ("dbi:connect" (cl-lookup-acl-operators-dbi-root "connect.htm"))
        ("dbi:db-external-format" (cl-lookup-acl-operators-dbi-root "db-external-format.htm"))
        ("dbi:db-hstmt" (cl-lookup-acl-operators-dbi-root "db-hstmt.htm"))
        ("dbi:db-non-blocking" (cl-lookup-acl-operators-dbi-root "db-non-blocking.htm"))
        ("dbi:db-width" (cl-lookup-acl-operators-dbi-root "db-width.htm"))
        ("dbi:disconnect" (cl-lookup-acl-operators-dbi-root "disconnect.htm"))
        ("dbi:end-transaction" (cl-lookup-acl-operators-dbi-root "end-transaction.htm"))
        ("dbi:fetch-row" (cl-lookup-acl-operators-dbi-root "fetch-row.htm"))
        ("dbi:list-all-database-tables" (cl-lookup-acl-operators-dbi-root "list-all-database-tables.htm"))
        ("dbi:list-all-table-columns" (cl-lookup-acl-operators-dbi-root "list-all-table-columns.htm"))
        ("dbi:loop-over-results" (cl-lookup-acl-operators-dbi-root "loop-over-results.htm"))
        ("dbi:odbc-error" (cl-lookup-acl-operators-dbi-root "odbc-error.htm"))
        ("dbi:odbc-error-width-too-small" (cl-lookup-acl-classes-dbi-root "odbc-error-width-too-small.htm"))
        ("dbi:prepare-sql" (cl-lookup-acl-operators-dbi-root "prepare-sql.htm"))
        ("dbi:rr-sql" (cl-lookup-acl-operators-dbi-root "rr-sql.htm"))
        ("dbi:run-prepared-sql" (cl-lookup-acl-operators-dbi-root "run-prepared-sql.htm"))
        ("dbi:set-autocommit" (cl-lookup-acl-operators-dbi-root "set-autocommit.htm"))
        ("dbi:sql" (cl-lookup-acl-operators-dbi-root "sql.htm"))
        ))

(provide 'cl-lookup-acl-dbi)